name: EC2 SSH Login

on:
  push:
    branches:
      - main

jobs:
  ssh-login:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH Key
      run: |
        echo "${{ secrets.CHATBOT_PEM }}" > ec2_key.pem
        chmod 600 ec2_key.pem

    - name: Log into EC2 instance and deploy
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
      run: |
        ssh -i ec2_key.pem -o StrictHostKeyChecking=no ubuntu@${EC2_HOST} << 'EOF'
          sudo apt update
          sudo apt install -y git docker-compose
          git clone https://github.com/ZeroWillHero/Anonymus-ChatBot.git || (cd Anonymus-ChatBot && git pull)
          cd Anonymus-ChatBot
          echo "PORT=${{ secrets.PORT }}" > .env
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> .env
          echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" >> .env
          echo ".env file created with environment variables"
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker-compose pull
          docker-compose up -d --build
          echo "Docker container started successfully"
        EOF