
name: EC2 SSH Login

on:
  push:
    branches:
      - main

jobs:
  ssh-login:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH Key
      run: |
        echo "${{ secrets.CHATBOT_PEM }}" > ec2_key.pem
        chmod 600 ec2_key.pem

    - name: Log into EC2 instance
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
      run: |
        ssh -i ec2_key.pem -o StrictHostKeyChecking=no ubuntu@${EC2_HOST} "echo 'Successfully logged into EC2'"
        sudo apt install git -y
        git clone https://github.com/ZeroWillHero/Anonymus-ChatBot.git
        cd Anonymus-ChatBot
          echo "PORT=${{ secrets.PORT }}" > .env
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> .env
          echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" >> .env
          echo ".env file created with environment variables"
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker compose build 
          docker tag anonymus-chatbot-app ${{ secrets.DOCKER_USERNAME }}/express_chatbot:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/express_chatbot:latest     
          docker compose up -d
          echo "Docker container started successfully"   

