name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Get EC2 instance public DNS
      id: dns
      run: |
        INSTANCE_ID=<your-existing-instance-id>
        PUBLIC_DNS=$(aws ec2 describe-instances --instance-ids $INSTANCE_ID --query 'Reservations[0].Instances[0].PublicDnsName' --output text)
        echo "::set-output name=public_dns::$PUBLIC_DNS"

    - name: Install Docker and MongoDB on EC2
      run: |
        PUBLIC_DNS=${{ steps.dns.outputs.public_dns }}
        ssh -o StrictHostKeyChecking=no -i chatbot.pem ubuntu@$PUBLIC_DNS << 'EOF'
          sudo apt-get update -y
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo usermod -aG docker ubuntu
          sudo apt-get install -y mongodb
          sudo systemctl start mongodb
          sudo systemctl enable mongodb
        EOF

    - name: Clone repository and deploy with Docker Compose
      run: |
        PUBLIC_DNS=${{ steps.dns.outputs.public_dns }}
        ssh -o StrictHostKeyChecking=no -i chatbot.pem ubuntu@$PUBLIC_DNS << 'EOF'
          git clone https://github.com/ZeroWillHero/Anonymus-ChatBot.git
          cd Anonymus-ChatBot
          sudo docker-compose up -d
        EOF
