name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Get EC2 instance public DNS
      id: dns
      run: |
        INSTANCE_ID=i-09d02807eeff6252b
        PUBLIC_DNS=$(aws ec2 describe-instances --instance-ids $INSTANCE_ID --query 'Reservations[0].Instances[0].PublicDnsName' --output text)
        echo "::set-output name=public_dns::$PUBLIC_DNS"

    - name: Add SSH key
      run: |
        echo "${{ secrets.CHATBOT_PEM }}" > chatbot.pem
        chmod 600 chatbot.pem

    - name: Install Docker and MongoDB on EC2
      run: |
        PUBLIC_DNS=${{ steps.dns.outputs.public_dns }}
        ssh -o StrictHostKeyChecking=no -i chatbot.pem ubuntu@$PUBLIC_DNS << 'EOF'
          sudo apt-get update -y
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo usermod -aG docker ubuntu

          # Install MongoDB
          wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | sudo apt-key add -
          echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.4.list
          sudo apt-get update -y
          sudo apt-get install -y mongodb-org
          sudo systemctl start mongod
          sudo systemctl enable mongod
        EOF

    - name: Deploy application
      run: |
        PUBLIC_DNS=${{ steps.dns.outputs.public_dns }}
        ssh -o StrictHostKeyChecking=no -i chatbot.pem ubuntu@$PUBLIC_DNS << 'EOF'
          cd /path/to/your/docker-compose-directory
          docker-compose pull
          docker-compose up -d
        EOF