name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build the Docker image
      run: docker compose build

    - name: Tag and push image
      run: |
        IMAGE_ID=$(docker images -q express_chatbot:latest)
        docker tag $IMAGE_ID ${{ secrets.DOCKER_USERNAME }}/express_chatbot:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/express_chatbot:latest

    

    


