name: Build and Push Docker Images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build the Docker images
      run: docker compose build

    - name: Tag and push app image
      run: |
        docker tag express_chatbot:latest ${{ secrets.DOCKER_USERNAME }}/express_chatbot:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/express_chatbot:latest

    - name: Tag and push mongo image
      run: |
        docker tag chatbot_mongo:latest ${{ secrets.DOCKER_USERNAME }}/chatbot_mongo:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/chatbot_mongo:latest