on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push app image
      run: |
        docker compose -f docker-compose.yaml build app
        docker tag express_chatbot:latest ${{ secrets.DOCKER_USERNAME }}/express_chatbot:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/express_chatbot:latest

    - name: Build and push mongo image
      run: |
        docker compose -f docker-compose.yaml build mongo
        docker tag chatbot_mongo:latest ${{ secrets.DOCKER_USERNAME }}/chatbot_mongo:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/chatbot_mongo:latest